server {
  listen 80;
  server_name localhost;

  root /usr/share/nginx/html;
  index index.html;

  location / {
    add_header Cross-Origin-Opener-Policy unsafe-none;
    try_files $uri $uri/ /index.html;
  }

}
